// Mocks generated by Mockito 5.2.0 from annotations
// in shop_clean_arch/test/app/shop/infra/repositories/auth_repository_implements_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shop_clean_arch/app/shop/domain/entities/auth.dart' as _i7;
import 'package:shop_clean_arch/app/shop/domain/exceptions/auth_exceptions.dart'
    as _i6;
import 'package:shop_clean_arch/app/shop/infra/datasources/auth_datasource.dart'
    as _i8;
import 'package:shop_clean_arch/app/shop/infra/models/auth_result_model.dart'
    as _i3;
import 'package:shop_clean_arch/app/shop/infra/repositories/auth_repository_implements.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeAuthResultModel_1 extends _i1.Fake implements _i3.AuthResultModel {}

/// A class which mocks [AuthRepositoryImplements].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryImplements extends _i1.Mock
    implements _i4.AuthRepositoryImplements {
  MockAuthRepositoryImplements() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.IAuthExceptions, _i7.Auth?>> authWithEmail(
          String? email, String? password) =>
      (super.noSuchMethod(Invocation.method(#authWithEmail, [email, password]),
          returnValue: Future<_i2.Either<_i6.IAuthExceptions, _i7.Auth?>>.value(
              _FakeEither_0<_i6.IAuthExceptions, _i7.Auth?>())) as _i5
          .Future<_i2.Either<_i6.IAuthExceptions, _i7.Auth?>>);
}

/// A class which mocks [IAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthDataSource extends _i1.Mock implements _i8.IAuthDataSource {
  MockIAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.AuthResultModel> authWithEmail(
          String? email, String? password) =>
      (super.noSuchMethod(Invocation.method(#authWithEmail, [email, password]),
              returnValue:
                  Future<_i3.AuthResultModel>.value(_FakeAuthResultModel_1()))
          as _i5.Future<_i3.AuthResultModel>);
}
